parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.

    pgsql.driver: 'pgsql'
    pgsql.version: 9.5
    pgsql.charset: 'utf8'


doctrine:
    dbal:
        default_connection: phpVDB
        connections:
            phpVDB:
                driver: '%pgsql.driver%'
                server_version: '%pgsql.version%'
                charset: '%pgsql.charset%'
                url: '%database.url.phpVDB%'
                mapping_types:
                    citext: text
                    cidr: string
                    macaddr: string

    orm:
        default_entity_manager: netCMDB
        entity_managers:
            netCMDB:
                connection: phpVDB
                mappings:
                    Company:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Company'
                        prefix: 'App\Entity\Company'
                        alias: Company
                    Equipment:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Equipment'
                        prefix: 'App\Entity\Equipment'
                        alias: Equipment
                    Geolocation:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Geolocation'
                        prefix: 'App\Entity\Geolocation'
                        alias: Geolocation
                    Network:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Network'
                        prefix: 'App\Entity\Network'
                        alias: Network
                    Storage_1C:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Storage_1C'
                        prefix: 'App\Entity\Storage_1C'
                        alias: Storage_1C
